### ISSUE TITLE
thrown MongoWriteException when launch scoold if enabled MongoDB integration

### ISSUE THREAD

**Issue by lufia** [Erudika/scoold#11]
I've written *docker-compose.yml* with some *Dockerfile*.
Simple setup(para+scoold) is fine.
But if setting up para with para-dao-mongodb-1.25.1-shaded.jar, MongoDB raises `MongoWriteException` when write settings.

[Updates Enforce Field Name Restrictions](https://docs.mongodb.com/manual/release-notes/2.6-compatibility/#updates-enforce-field-name-restrictions) says:

> Updates no longer support saving field names that contain a dot (.)
> or a field name that starts with a dollar sign ($).

```console
scoold_1     | 2017-10-10 05:57:32 [INFO ] Initialized ParaClient with endpoint http://para:8080 and access key 'app:scoold'.
scoold_1     | 2017-10-10 05:57:32 [DEBUG] PUT /v1/_settings, entity: Entity{entity={gh_app_id=, gh_secret=, security.ldap.bind_dn=, security.ldap.user_dn_pattern=, security.ldap.server_url=, security.ldap.base_dn=, ms_app_id=, security.ldap.bind_pass=, signin_success=http://localhost:8000/signin/success?jwt=?, security.ldap.user_search_filter=, in_app_id=, in_secret=, tw_secret=, security.ldap.user_search_base=, tw_app_id=, security.ldap.active_directory_domain=, ms_secret=, security.ldap.password_attribute=, signin_failure=http://localhost:8000/signin?code=3&error=true}, variant=Variant[mediaType=application/json, language=null, encoding=null], annotations=[]}
para_1       | 2017-10-10 05:57:33 [ERROR] null
para_1       | com.mongodb.MongoWriteException: The dotted field 'security.ldap.bind_dn' in 'settings.security.ldap.bind_dn' is not valid for storage.
para_1       | 	at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:558)
para_1       | 	at com.mongodb.MongoCollectionImpl.update(MongoCollectionImpl.java:542)
para_1       | 	at com.mongodb.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:381)
para_1       | 	at com.mongodb.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:376)
para_1       | 	at com.erudika.para.persistence.MongoDBDAO.updateRow(MongoDBDAO.java:161)
para_1       | 	at com.erudika.para.persistence.MongoDBDAO.update(MongoDBDAO.java:124)
para_1       | 	at com.erudika.para.persistence.MongoDBDAO$$EnhancerByGuice$$b90184b4.CGLIB$update$10(<generated>)
para_1       | 	at com.erudika.para.persistence.MongoDBDAO$$EnhancerByGuice$$b90184b4$$FastClassByGuice$$3c2ac843.invoke(<generated>)
para_1       | 	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
para_1       | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
para_1       | 	at com.erudika.para.aop.IndexAndCacheAspect.addToIndexOperation(IndexAndCacheAspect.java:205)
para_1       | 	at com.erudika.para.aop.IndexAndCacheAspect.handleIndexing(IndexAndCacheAspect.java:150)
para_1       | 	at com.erudika.para.aop.IndexAndCacheAspect.invoke(IndexAndCacheAspect.java:123)
para_1       | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
para_1       | 	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
para_1       | 	at com.erudika.para.persistence.MongoDBDAO$$EnhancerByGuice$$b90184b4.update(<generated>)
para_1       | 	at com.erudika.para.core.App.update(App.java:1059)
para_1       | 	at com.erudika.para.rest.Api1$20.apply(Api1.java:635)
para_1       | 	at com.erudika.para.rest.Api1$20.apply(Api1.java:621)
para_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
para_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
para_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
para_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
para_1       | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
para_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
para_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
para_1       | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
para_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
para_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
para_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
para_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
para_1       | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
para_1       | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
para_1       | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
para_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
para_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
para_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
para_1       | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
para_1       | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
para_1       | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
para_1       | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
para_1       | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
para_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
para_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
para_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
para_1       | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
para_1       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
para_1       | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
para_1       | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at com.erudika.para.security.RestAuthFilter.doFilter(RestAuthFilter.java:99)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at com.erudika.para.security.JWTRestfulAuthFilter.doFilter(JWTRestfulAuthFilter.java:125)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
para_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
para_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
para_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
para_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
para_1       | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
para_1       | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
para_1       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
para_1       | 	at com.erudika.para.utils.filters.CORSFilter.handleNonCORS(CORSFilter.java:415)
para_1       | 	at com.erudika.para.utils.filters.CORSFilter.doFilter(CORSFilter.java:164)
para_1       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
para_1       | 	at com.erudika.para.utils.filters.ErrorFilter.doFilter(ErrorFilter.java:59)
para_1       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
para_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
para_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
para_1       | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
para_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
para_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
para_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
para_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
para_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
para_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
para_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
para_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
para_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
para_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
para_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
para_1       | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
para_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
para_1       | 	at org.eclipse.jetty.server.Server.handle(Server.java:564)
para_1       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
para_1       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
para_1       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
para_1       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
para_1       | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
para_1       | 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
para_1       | 	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
para_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
para_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
para_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
para_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
para_1       | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by albogdano** [comment]
Thank you for reporting this! I’ll have a look later today. I wasn’t aware of this restriction but it should be an easy fix.

**Comment by lufia** [comment]
@albogdano thank you for your quick fix.
