### ISSUE TITLE
oauth2_auth only scoold Pro feature?

### ISSUE THREAD

**Issue by bjoern-flagbit** [Erudika/scoold#210]
Have scoold running and also oauth2 app with MS Azure.
Authentication is working at least login is succesful in Azure.

But where to redirect after successful login?
In documentation I always read `https://para_url/oauth2_auth`
Is this the para backend or the scoold frontend url?

I tried both. 

If it is backend I only get a 200er with a white page. Some redirect missing?
If it is frontend I only get a 404er page.

Thx for some hint.

**Comment by albogdano** [comment]
All authentication methods are supported by both versions of Scoold. OAuth2 is not a Pro feature.
The redirect on success always points to the URL of your Para server. So "para_url" would be the URL of your Para server, a.k.a. backend. You may have to add this property to your Scoold configuration:
`para.security.redirect_uri = "http://para_public_url:port"`

See this issue for more info: #199

**Comment by bjoern-flagbit** [comment]
If I use this config:
```
  para_host_url: "https://frontend-scoold.cloud"
  para_endpoint: "https://backend-para.cloud"
  para_security_redirect_uri : "https://frontend-scoold.cloud"
```
I will be redirected to scoold frontend with 404. So this is in general wrong I think.

---

If I use this config:
```
  para_host_url: "https://frontend-scoold.cloud"
  para_endpoint: "https://backend-para.cloud"
  para_security_redirect_uri : "https://backend-para.cloud"
```
I will be redirected to para backend with only a white screen.

Maybe my problem is that in our k8s cluster we can not use http.

I also found this error message in para log:
```
2020-12-17 07:59:39,598 [ERROR] c.e.para.utils.filters.ErrorFilter - null                                                                                                                     
org.apache.http.client.ClientProtocolException: null                                                                                                                                          
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)                                                                                              
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)                                                                                               
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)                                                                                              
        at com.erudika.para.security.filters.GenericOAuth2Filter.tokenRequest(GenericOAuth2Filter.java:358)                                                                                   
        at com.erudika.para.security.filters.GenericOAuth2Filter.attemptAuthentication(GenericOAuth2Filter.java:122)                                                                          
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:222) 
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)                                   
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)                                   
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)                                   
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)                                   
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)                                   
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)                                                                                
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)                                                                                 
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:115)                                                                                             
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)                                                                                        
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)                                                                              
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)                                                                            
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)                                                                                        
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)                                                      
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)                                                       
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)                                 
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)                                                                                        
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)                                                                           
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)                                                                                      
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)   
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)                                                                                                             
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)                                                                                                  
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)                                                                                                         
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)                                                                                                      
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)                                                                                                        
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)                                                                                                    
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)                                                                                                  
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)                                                                                                 
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)                                                                                                  
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)                                                                                                 
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)                                                                                                   
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)                                                                                                          
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)                                                                                                  
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)                                                                                                   
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)                                                                                                  
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)                                                                                                      
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)                                                                                              
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)                                                                                                    
        at org.eclipse.jetty.server.Server.handle(Server.java:516)                                                                                                                            
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)                                                                                                         
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)                                                                                                                
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)                                                                                                                  
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)                                                                                                        
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)                                                                                        
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)                                                                                                                  
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)                                                                                                               
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)                                                                                                   
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)                                                                                               
        at java.lang.Thread.run(Thread.java:748)                                                                                                                                              
Caused by: org.apache.http.ProtocolException: Target host is not specified                                                                                                                    
        at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)                                                                                          
        at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)                                                                                         
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)                                                                                              
        ... 87 common frames omitted  
```

Looks like "target host" is missing in para config.

**Comment by albogdano** [comment]
What is your configuration for `para.security.oauth.token_url`? It must be a valid URL starting with `http(s)://`.

**Comment by bjoern-flagbit** [comment]
Looks like this (just removed some parts for directory id):
`para_security_oauth_token_url: "https://login.microsoftonline.com/8b...eb2a3/oauth2/v2.0/token"`

Like I said in Azure I can see a "success" login.

**Comment by albogdano** [comment]
Are you sure you want to be using environment variables for this because `para_security_oauth_token_url` is meant to be loaded from ENV. Usually Scoold loads the configuration file with all the settings in it, including `para.security.oauth.token_url`

**Comment by bjoern-flagbit** [comment]
We use a configmap (YAML) in k8s. And the environment variables get applied. This works well and we can change config fast.

**Comment by albogdano** [comment]
Ok, but are you sure your configuration is picked up Scoold properly? That exception means that the value of `para.security.oauth.token_url` is missing, invalid or blank. You can verify that the configuration is picked up by checking the stored settings in your Para app using `GET para-host/v1/_settings` or `paraClient.getSettings()`

**Comment by bjoern-flagbit** [comment]
Yes. I am sure about this that Scoold pick this up properly.
I activated registration via form and then Scoold told me that I need to setup SMTP.
Created an SMTP User in AWS added to Scoold configmap and the message was gone.

Tried to register, but then I get this kind of error ... maybe something is wrong with the used docker image ... 
```
2020-12-17 10:01:31,808 [WARN ] o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]                             
2020-12-17 10:01:31,857 [ERROR] com.erudika.para.client.ParaClient - 405 - Method Not Allowed  
```

**Comment by albogdano** [comment]
Ok, so where do you load `para_security_oauth_token_url` from and into - do you load it from the container environment and into Scoold? It should be loaded into Scoold.

**Comment by albogdano** [comment]
Also can you check if the property `security.oauth.token_url` is actually stored in the settings field inside your Para `app` object.

**Comment by bjoern-flagbit** [comment]
I created local scoold docker container, using now https://paraio.com/ as backend and config file like you mentioned.
I can get my login credentials when I post to https://paraio.com/jwt_auth with insomnia.
User creation was working within the frontend container.

But when I try to login ... I now get this error:
`2020-12-17 12:54:35,226 [ERROR] com.erudika.para.client.ParaClient - 403 - Invalid signature for request GET /v1/_id/bjoern.meyer%40flagbit.de coming from app  flagbit-qa`

And yes I read https://github.com/Erudika/scoold/issues/141

But I used the default docker-image and there is NO apache.
https://github.com/Erudika/scoold/blob/master/docker-compose.yml
Scoold docker container depends on https://hub.docker.com/_/openjdk

Any idea about this? By the way. Thx for your help!

**Comment by albogdano** [comment]
Yes, even though you aren't using Apache, Kubernetes may still be modifying the request somehow and break its signature.
Everytime somebody asks for help with Scoold on K8s or Docker they usually have similar connectivity issues like you and my suggestion is to try and make your configuration work outside of Docker and then deploy it back to K8s/Docker. There are just too many layers and moving parts here and I can't exactly say what is wrong. So, try starting Scoold from the command line as `java -jar -Dconfig.file=./application.conf scoold-*.jar`, test the OAuth2 settings and it it all works as expected, continue with k8s.
Keep in mind that ENV configuration properties contain `_` instead of dots `.`.

You should also definitely check the settings map inside your Para app object with `id` `app:flagbit-qa`. If the settings don't contain `token_url` you have some sort of communication issue between Scoold and Para, or the Scoold config is not picked up correctly.

**Comment by bjoern-flagbit** [comment]
I was now using your helm chart. 
And with this and https://paraio.com/ as backend it looks like working now.
Again thx a lot. What a day. :+1: 

By the way. I like the api documentation and the para-cli. :heart:

**Comment by albogdano** [comment]
Thanks for the positive feedback! If you have any other issues, don't hesitate to create a new post here or come join the chat [on Gitter](https://gitter.im/Erudika/scoold)
