### ISSUE TITLE
Google cloud build fails with "No deployable artifacts were found"

### ISSUE THREAD

**Issue by k-one-o-two** [Erudika/scoold#364]
Trying to deploy to the google cloud via cli using
```
gcloud app deploy app.gae.yaml
```
But keep getting the following error:
```
tarting Step #1
Step #1: Pulling image: gcr.io/gcp-runtimes/java/runtime-builder@sha256:7fe8746e5e7c6c374a4940667a8ad9059d793469ba23141672ecd816b7bba4a4
Step #1: gcr.io/gcp-runtimes/java/runtime-builder@sha256:7fe8746e5e7c6c374a4940667a8ad9059d793469ba23141672ecd816b7bba4a4: Pulling from gcp-runtimes/java/runtime-builder
Step #1: Digest: sha256:7fe8746e5e7c6c374a4940667a8ad9059d793469ba23141672ecd816b7bba4a4
Step #1: Status: Downloaded newer image for gcr.io/gcp-runtimes/java/runtime-builder@sha256:7fe8746e5e7c6c374a4940667a8ad9059d793469ba23141672ecd816b7bba4a4
Step #1: gcr.io/gcp-runtimes/java/runtime-builder@sha256:7fe8746e5e7c6c374a4940667a8ad9059d793469ba23141672ecd816b7bba4a4
Step #1: Exception in thread "main" com.google.cloud.runtimes.builder.exception.ArtifactNotFoundException: No deployable artifacts were found. Unable to proceed.
Step #1: 	at com.google.cloud.runtimes.builder.buildsteps.PrebuiltRuntimeImageBuildStep.getArtifact(PrebuiltRuntimeImageBuildStep.java:77)
Step #1: 	at com.google.cloud.runtimes.builder.buildsteps.RuntimeImageBuildStep.run(RuntimeImageBuildStep.java:50)
Step #1: 	at com.google.cloud.runtimes.builder.BuildPipelineConfigurator.generateDockerResources(BuildPipelineConfigurator.java:104)
Step #1: 	at com.google.cloud.runtimes.builder.Application.main(Application.java:147)
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/gcp-runtimes/java/runtime-builder@sha256:7fe8746e5e7c6c374a4940667a8ad9059d793469ba23141672ecd816b7bba4a4" failed: step exited with non-zero status: 1
```

**Comment by albogdano** [comment]
See here https://github.com/Erudika/scoold#deploying-scoold-to-google-app-engine for details.

Another good tutorial: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot#0

**Comment by kirill-cronvall** [comment]
@albogdano yes, this is where I come from. I have managed to do that via building an image locally and then uploading it using `gcloud builds submit` command. But the one in the docs is still not working for me, maybe I’m doing something wrong?

**Comment by albogdano** [comment]
I updated the README to clarify the steps and I also updated the YAML file to include this:
```
handlers:
  - url: /.*
  script: scoold.jar
```
That may have been the problem. I'm sorry but I am not an expert on GAE so this is as much help as I can give you.
